[build]
  publish = "dist"
  command = "vite build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/favicons/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
